// Code generated by go-tizot v0-2024a.0.1, DO NOT EDIT.
package examples

import (
	"slices"
	"strings"
	"time"
)

type Zone struct {
	ID          string
	Transitions []Transition
	Rules       []Rule
}

type Transition struct {
	When         time.Time
	OffsetBefore time.Duration
	OffsetAfter  time.Duration
}

type RuleType string

const (
	RuleTypeWeekDayPositive  RuleType = "net.jumpaku.tzot.Rule.WeekDayPositive"
	RuleTypeWeekDayNegative  RuleType = "net.jumpaku.tzot.Rule.WeekDayNegative"
	RuleTypeMonthDayPositive RuleType = "net.jumpaku.tzot.Rule.MonthDayPositive"
	RuleTypeMonthDayNegative RuleType = "net.jumpaku.tzot.Rule.MonthDayNegative"
)

type Rule struct {
	RuleType          RuleType
	OffsetBefore      time.Duration
	OffsetAfter       time.Duration
	Month             time.Month
	TimeOffset        time.Duration
	TimeHour          int
	TimeMinute        int
	TimeSecond        int
	DayOfWeek         time.Weekday
	MonthDays         int
	MonthDaysFromLast int
}

func AvailableZoneIDs() []string {
	return append([]string{}, zoneIDs...)
}

func GetZone(zoneID string) (zone Zone, found bool) {
	zone, found = zones[zoneID]
	return zone, found
}

func GetTZVersion() string {
	return strings.TrimSpace("2024a")
}

var zoneIDs = func() []string {
	zoneIDs := []string{}
	for zoneID := range zones {
		zoneIDs = append(zoneIDs, zoneID)
	}
	slices.Sort(zoneIDs)
	return zoneIDs
}()

var zones = map[string]Zone{
	"Asia/Tokyo": {
		ID: "Asia/Tokyo",
		Transitions: []Transition{
			{
				When:         time.Unix(-2587712400, 0),
				OffsetBefore: 33539000000000,
				OffsetAfter:  32400000000000,
			},
			{
				When:         time.Unix(-683802000, 0),
				OffsetBefore: 32400000000000,
				OffsetAfter:  36000000000000,
			},
			{
				When:         time.Unix(-672310800, 0),
				OffsetBefore: 36000000000000,
				OffsetAfter:  32400000000000,
			},
			{
				When:         time.Unix(-654771600, 0),
				OffsetBefore: 32400000000000,
				OffsetAfter:  36000000000000,
			},
			{
				When:         time.Unix(-640861200, 0),
				OffsetBefore: 36000000000000,
				OffsetAfter:  32400000000000,
			},
			{
				When:         time.Unix(-620298000, 0),
				OffsetBefore: 32400000000000,
				OffsetAfter:  36000000000000,
			},
			{
				When:         time.Unix(-609411600, 0),
				OffsetBefore: 36000000000000,
				OffsetAfter:  32400000000000,
			},
			{
				When:         time.Unix(-588848400, 0),
				OffsetBefore: 32400000000000,
				OffsetAfter:  36000000000000,
			},
			{
				When:         time.Unix(-577962000, 0),
				OffsetBefore: 36000000000000,
				OffsetAfter:  32400000000000,
			},
		},
		Rules: []Rule{},
	},
	"Pacific/Apia": {
		ID: "Pacific/Apia",
		Transitions: []Transition{
			{
				When:         time.Unix(-2445424384, 0),
				OffsetBefore: 45184000000000,
				OffsetAfter:  -41216000000000,
			},
			{
				When:         time.Unix(-1861878784, 0),
				OffsetBefore: -41216000000000,
				OffsetAfter:  -41400000000000,
			},
			{
				When:         time.Unix(-631110600, 0),
				OffsetBefore: -41400000000000,
				OffsetAfter:  -39600000000000,
			},
			{
				When:         time.Unix(1285498800, 0),
				OffsetBefore: -39600000000000,
				OffsetAfter:  -36000000000000,
			},
			{
				When:         time.Unix(1301752800, 0),
				OffsetBefore: -36000000000000,
				OffsetAfter:  -39600000000000,
			},
			{
				When:         time.Unix(1316872800, 0),
				OffsetBefore: -39600000000000,
				OffsetAfter:  -36000000000000,
			},
			{
				When:         time.Unix(1325239200, 0),
				OffsetBefore: -36000000000000,
				OffsetAfter:  50400000000000,
			},
			{
				When:         time.Unix(1333202400, 0),
				OffsetBefore: 50400000000000,
				OffsetAfter:  46800000000000,
			},
			{
				When:         time.Unix(1348927200, 0),
				OffsetBefore: 46800000000000,
				OffsetAfter:  50400000000000,
			},
			{
				When:         time.Unix(1365256800, 0),
				OffsetBefore: 50400000000000,
				OffsetAfter:  46800000000000,
			},
			{
				When:         time.Unix(1380376800, 0),
				OffsetBefore: 46800000000000,
				OffsetAfter:  50400000000000,
			},
			{
				When:         time.Unix(1396706400, 0),
				OffsetBefore: 50400000000000,
				OffsetAfter:  46800000000000,
			},
			{
				When:         time.Unix(1411826400, 0),
				OffsetBefore: 46800000000000,
				OffsetAfter:  50400000000000,
			},
			{
				When:         time.Unix(1428156000, 0),
				OffsetBefore: 50400000000000,
				OffsetAfter:  46800000000000,
			},
			{
				When:         time.Unix(1443276000, 0),
				OffsetBefore: 46800000000000,
				OffsetAfter:  50400000000000,
			},
			{
				When:         time.Unix(1459605600, 0),
				OffsetBefore: 50400000000000,
				OffsetAfter:  46800000000000,
			},
			{
				When:         time.Unix(1474725600, 0),
				OffsetBefore: 46800000000000,
				OffsetAfter:  50400000000000,
			},
			{
				When:         time.Unix(1491055200, 0),
				OffsetBefore: 50400000000000,
				OffsetAfter:  46800000000000,
			},
			{
				When:         time.Unix(1506175200, 0),
				OffsetBefore: 46800000000000,
				OffsetAfter:  50400000000000,
			},
			{
				When:         time.Unix(1522504800, 0),
				OffsetBefore: 50400000000000,
				OffsetAfter:  46800000000000,
			},
			{
				When:         time.Unix(1538229600, 0),
				OffsetBefore: 46800000000000,
				OffsetAfter:  50400000000000,
			},
			{
				When:         time.Unix(1554559200, 0),
				OffsetBefore: 50400000000000,
				OffsetAfter:  46800000000000,
			},
			{
				When:         time.Unix(1569679200, 0),
				OffsetBefore: 46800000000000,
				OffsetAfter:  50400000000000,
			},
			{
				When:         time.Unix(1586008800, 0),
				OffsetBefore: 50400000000000,
				OffsetAfter:  46800000000000,
			},
			{
				When:         time.Unix(1601128800, 0),
				OffsetBefore: 46800000000000,
				OffsetAfter:  50400000000000,
			},
			{
				When:         time.Unix(1617458400, 0),
				OffsetBefore: 50400000000000,
				OffsetAfter:  46800000000000,
			},
		},
		Rules: []Rule{},
	},
	"Europe/Zurich": {
		ID: "Europe/Zurich",
		Transitions: []Transition{
			{
				When:         time.Unix(-3675198848, 0),
				OffsetBefore: 2048000000000,
				OffsetAfter:  1786000000000,
			},
			{
				When:         time.Unix(-2385246586, 0),
				OffsetBefore: 1786000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(-904435200, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(-891129600, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(-872985600, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(-859680000, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(354675600, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(370400400, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(386125200, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(401850000, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(417574800, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(433299600, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(449024400, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(465354000, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(481078800, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(496803600, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(512528400, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(528253200, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(543978000, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(559702800, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(575427600, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(591152400, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(606877200, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(622602000, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(638326800, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(654656400, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(670381200, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(686106000, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(701830800, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(717555600, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(733280400, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(749005200, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(764730000, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(780454800, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(796179600, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(811904400, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(828234000, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(846378000, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(859683600, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(877827600, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
		},
		Rules: []Rule{
			{
				RuleType:          "net.jumpaku.tzot.Rule.WeekDayPositive",
				OffsetBefore:      3600000000000,
				OffsetAfter:       7200000000000,
				Month:             3,
				TimeOffset:        0,
				TimeHour:          1,
				TimeMinute:        0,
				TimeSecond:        0,
				DayOfWeek:         7,
				MonthDays:         25,
				MonthDaysFromLast: 0,
			},
			{
				RuleType:          "net.jumpaku.tzot.Rule.WeekDayPositive",
				OffsetBefore:      7200000000000,
				OffsetAfter:       3600000000000,
				Month:             10,
				TimeOffset:        0,
				TimeHour:          1,
				TimeMinute:        0,
				TimeSecond:        0,
				DayOfWeek:         7,
				MonthDays:         25,
				MonthDaysFromLast: 0,
			},
		},
	},
	"Zulu": {
		ID:          "Zulu",
		Transitions: []Transition{},
		Rules:       []Rule{},
	},
}
