// Code generated by go-tizot v0.0.1, DO NOT EDIT.
package examples

import (
	"slices"
	"strings"
	"time"
)

type Zone struct {
	ID          string
	Transitions []Transition
}

type Transition struct {
	When         time.Time
	OffsetBefore time.Duration
	OffsetAfter  time.Duration
}

func AvailableZoneIDs() []string {
	return append([]string{}, zoneIDs...)
}

func GetZone(zoneID string) (zone Zone, found bool) {
	zone, found = zones[zoneID]
	return zone, found
}

func GetTZVersion() string {
	return strings.TrimSpace("2024a")
}

var zoneIDs = func() []string {
	zoneIDs := []string{}
	for zoneID := range zones {
		zoneIDs = append(zoneIDs, zoneID)
	}
	slices.Sort(zoneIDs)
	return zoneIDs
}()

var zones = map[string]Zone{
	"Asia/Tokyo": {
		ID: "Asia/Tokyo",
		Transitions: []Transition{
			{
				When:         time.Unix(-2587712400, 0),
				OffsetBefore: 33539000000000,
				OffsetAfter:  32400000000000,
			},
			{
				When:         time.Unix(-683802000, 0),
				OffsetBefore: 32400000000000,
				OffsetAfter:  36000000000000,
			},
			{
				When:         time.Unix(-672310800, 0),
				OffsetBefore: 36000000000000,
				OffsetAfter:  32400000000000,
			},
			{
				When:         time.Unix(-654771600, 0),
				OffsetBefore: 32400000000000,
				OffsetAfter:  36000000000000,
			},
			{
				When:         time.Unix(-640861200, 0),
				OffsetBefore: 36000000000000,
				OffsetAfter:  32400000000000,
			},
			{
				When:         time.Unix(-620298000, 0),
				OffsetBefore: 32400000000000,
				OffsetAfter:  36000000000000,
			},
			{
				When:         time.Unix(-609411600, 0),
				OffsetBefore: 36000000000000,
				OffsetAfter:  32400000000000,
			},
			{
				When:         time.Unix(-588848400, 0),
				OffsetBefore: 32400000000000,
				OffsetAfter:  36000000000000,
			},
			{
				When:         time.Unix(-577962000, 0),
				OffsetBefore: 36000000000000,
				OffsetAfter:  32400000000000,
			},
		},
	},
	"Pacific/Pago_Pago": {
		ID: "Pacific/Pago_Pago",
		Transitions: []Transition{
			{
				When:         time.Unix(-2445424632, 0),
				OffsetBefore: 45432000000000,
				OffsetAfter:  -40968000000000,
			},
			{
				When:         time.Unix(-1861879032, 0),
				OffsetBefore: -40968000000000,
				OffsetAfter:  -39600000000000,
			},
		},
	},
	"Europe/Zurich": {
		ID: "Europe/Zurich",
		Transitions: []Transition{
			{
				When:         time.Unix(-3675198848, 0),
				OffsetBefore: 2048000000000,
				OffsetAfter:  1786000000000,
			},
			{
				When:         time.Unix(-2385246586, 0),
				OffsetBefore: 1786000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(-904435200, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(-891129600, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(-872985600, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(-859680000, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(354675600, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(370400400, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(386125200, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(401850000, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(417574800, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(433299600, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(449024400, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(465354000, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(481078800, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(496803600, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(512528400, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(528253200, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(543978000, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(559702800, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(575427600, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(591152400, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(606877200, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(622602000, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(638326800, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(654656400, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(670381200, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(686106000, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(701830800, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(717555600, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(733280400, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(749005200, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(764730000, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(780454800, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(796179600, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(811904400, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(828234000, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(846378000, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
			{
				When:         time.Unix(859683600, 0),
				OffsetBefore: 3600000000000,
				OffsetAfter:  7200000000000,
			},
			{
				When:         time.Unix(877827600, 0),
				OffsetBefore: 7200000000000,
				OffsetAfter:  3600000000000,
			},
		},
	},
	"Zulu": {
		ID:          "Zulu",
		Transitions: []Transition{},
	},
}
